### PR TITLE
fix mapping generation for nested objects with key 'type'

### LINKED ISSUE #178: mapping not generated if a field has key 'type'
I'm dealing with a schema that contains a field that goes by the name of `type` (think `'drama'`, `'comedy'` etc. for a Book schema), i.e.,
```js
{
// [...]
    book: {
      type: {
        type: String,
        es_indexed: true,
      },
      title: string,
    },
// [...]
}
```
This configuration prevents the mapping to be generated by mongoosastic. This is because of [this piece of code](https://github.com/mongoosastic/mongoosastic/blob/master/lib/mapping-generator.js#L59).

Ideas for a fix/workaround? (Unfortunately, we cannot change the name of the key.)

### PR DESCRIPTION
**Pull request by andrenarchy**
fixes #178

### CODE REVIEW

**Comment by nschloe** [comment]
I can confirm that this fixes the issue.

**Comment by jbdemonte** [comment]
I guess this is a duplicate of https://github.com/jbdemonte/mongoosastic/commit/66fd6372aace4ef27b90254c318ebaf435db879b

**Comment by andrenarchy** [comment]
@jbdemonte is there a PR for your fix?

**Comment by jbdemonte** [comment]
@andrenarchy my PR has been merged (https://github.com/mongoosastic/mongoosastic/pull/177)

**Comment by guumaster** [comment]
I'm closing this due to tests not passing and maybe already merged in #177. Please reopen if you have any question. Thanks.

**Pull request closed without merging**
