### PR TITLE
added support for suggesters

### PR DESCRIPTION
**Pull request by jmaza**
Hi! I'm using mongoosastic for a project, and I wanted to create an autocomplete using suggesters: https://www.elastic.co/guide/en/elasticsearch/reference/current/search-suggesters-completion.html 

But I noticed that I wasn't able to generate the required syntax, as 'suggest' has to be right next to 'query'. I noticed that by adding a few lines of code I could achieve what I wanted, and perform queries with a suggester. 

Let me know what you think :)

### CODE REVIEW

**Comment by basiclaser** [comment]
jmaza, can you please share an example of a working suggest field ? I copied the one from the test you wrote, but that caused my schema to not be 'missing'
```
    title: {
      type: String,
      es_type: 'completion',
      es_analyzer: 'simple',
      es_indexed: true
    },
```
and I also wrote a multi_field version, but it returns no results.
```
    title: {
      type: String,
      required: true,
      es_indexed: true,
      es_type: 'multi_field',
      es_fields: {
        not_analyzed: { type: 'string', index: 'not_analyzed' },
        suggested: { type: 'completion', analyzer: 'simple', payloads: true }
      }
    },
```
I was hoping you could elaborate on the usage of suggesters with mongoosastic! I'm stumped

**Comment by jmaza** [comment]
After you create the mapping using the .createMapping() method, you can create queries in the following way:
 
```
Kitten.search({
        match_all: {}
      }, {
          suggest: {
            kittensuggest: {
              text: 'Cook',
              completion: {
                field: 'name'
              }
            }
          }
        }, function(err, res) {
          // console.log(res.suggest)
        });
```

**Comment by basiclaser** [comment]
This is already present in my project: 
```    
promisify(DocumentRevision.createMapping, {context: DocumentRevision})(),
```
and when i hit the root endpoint i can see the mapping for the field which looks like this: 
```
                    },
                    "title": {
                        "type": "completion",
                        "analyzer": "simple",
                        "payloads": false,
                        "preserve_separators": true,
                        "preserve_position_increments": true,
                        "max_input_length": 50,
                        "fields": {
                            "analyzed": {
                                "type": "string"
                            },
                            "not_analyzed": {
                                "type": "string",
                                "index": "not_analyzed"
                            },
                            "suggested": {
                                "type": "completion",
                                "analyzer": "simple",
                                "payloads": true,
                                "preserve_separators": true,
                                "preserve_position_increments": true,
                                "max_input_length": 50
                            }
                        }
                    }
```
( Full mapping, maybe i missed something : https://ghostbin.com/paste/dyeg2 )

Yet when i hit the index with a basic query `http://192.168.99.100:9200/my_index/_search?q=a` , i get zero hits. I don't even expect suggestions at that endpoint (for that i'd use _suggest right?), but i get totally nothing which is odd. If I switch the title mapping back to a more generic setting, 
```
    title: {
      type: String,
      es_indexed: true,
      es_index: 'not_analyzed',
    },
```
I get typical results at the endpoint. 

Penny for your thoughts good Sir

**Comment by basiclaser** [comment]
ah, I managed to get it working with the following syntax, now requesting a 'suggest' on title.suggested works. The issue was the superfluous `es_type: 'multi_field',` that i included on the title field, which is now removed:
```
    title: {
      type: String,
      required: true,
      //es_type: 'multi_field',
      es_indexed: true,
      es_fields: {
        suggested: { type: 'completion', analyzer: 'simple', payloads: true },
        not_analyzed: { type: 'string', index: 'not_analyzed' }
      }
    },
```

**Pull request merged**
