### PR TITLE
Forwarding elasticsearch promises

### PR DESCRIPTION
**Pull request by mateusfreira**
Fixing #149 
This merge request Forward the promise from elasticsearch of search method,
Then fixed a Thiny error at test/config.js:32
All old features still working and 2 new unit tests were added.

### CODE REVIEW

**Comment by guumaster** [comment]
I think we should add promise for all methods of the plugin and not only to the `search()` method.

**Comment by DerekDomino** [comment]
Thanks @mateusfreira ! It sounds great.

However, Bluebird considers using defer() in contexts where the deferred asynchronism is already promisified as being an anti-pattern (https://github.com/petkaantonov/bluebird/wiki/Promise-anti-patterns).

The official Elasticsearch client library for Node.js supports promises. Mongoosastic could propagate them, sketched code:
```js
if (cb) {
    // Callback provided
    query.exec(function(err, docs) {
        ... // error handling and hydration

        cb(docs)

    });
} else {
   // promise requested
   return query.exec()
       .then(function(docs) {
             ... // hydration
       });
}
```

By this way the user can customize the promise provider (Q, Bluebird, ...) through the official Elastic search library:
```js
var elasticsearch = require('elasticsearch');
var bluebird = require('bluebird');

var client = new elasticsearch.Client({
  host: 'localhost:9200',
  log: 'trace',
  defer: function () {
    return Bluebird.defer();
  }
});
```

Mongoose handles promise provider injection in another way (quoting v4.3.7 doc): 
```js
   // Use native promises
    mongoose.Promise = global.Promise;
    assert.equal(query.exec().constructor, global.Promise);

    // Use bluebird
    mongoose.Promise = require('bluebird');
    assert.equal(query.exec().constructor, require('bluebird'));

    // Use q. Note that you **must** use `require('q').Promise`.
    mongoose.Promise = require('q').Promise;
    assert.ok(query.exec() instanceof require('q').makePromise);
```

https://github.com/Automattic/mongoose/blob/master/lib/promise_provider.js

**Comment by mateusfreira** [comment]
@DerekDomino tanks for your reply, I've solved the issues reported by you, can you take a look at the current implementation. There is something else I can improve in this MR?

**Comment by mateusfreira** [comment]
@guumaster I agree we should add promises for all methods, I've tried to start from a small part to see if would be interesting to the project be 'promise based ' natively.
I'll send a MR with a complete support for promissies as soon as I can finish it...

**Comment by DerekDomino** [comment]
I had see that Mongoose was refactoring the way they handle whether a callback is provided or not. I cannot find again where it is happening (in Mongoose' issues or PRs ...).

**Comment by guumaster** [comment]
major changes to the code. please review and reopen if necessary.

**Pull request closed without merging**
