### PR TITLE
Changed 'string' type to 'text' by default to support Elasticsearch 6.X

### PR DESCRIPTION
**Pull request by avadhpatel**
Also fixed tons of tests to pass with Elasticsearch 6.X and
elasticsearch.js 14.1.0 version.

Signed-off-by: Avadh Patel <avadh4all@gmail.com>

### CODE REVIEW

**Comment by guumaster** [comment]
Tests are failing, maybe due to elastic version available in travis. Could you please specify exactly which version where you using (node/mongo/elasticsearch) so I can try it locally? Thanks.

**Comment by avadhpatel** [comment]
I am using Elasticsearch 6.2 with elasticsearch.js 14.1.0

**Comment by idibidiart** [comment]
Status?

**Comment by avadhpatel** [comment]
I am using elastic 6.2 on ubuntu 17.04

**Comment by crutchcorn** [comment]
Has there been any progress on this?

**Comment by arpithparikh** [comment]
Does anyone see any progress on this?

**Comment by Elyx0** [comment]
Bumping aswell

**Comment by guumaster** [comment]
We have our deps updated to support latest version of the elasticsearch package. 

I'm closing this due to conflict with the `master` branch. Feel free to open a new PR against `develop` branch if you think something is missing.

Thanks!

**Pull request closed without merging**
