### PR TITLE
Allow tranform func to be async

### PR DESCRIPTION
**Pull request by callumgare**
If the user passes in an async function for the transform option then mongoosastic will silently the ditch all fields in the document being indexed in elasticsearch. This is because it doesn't understand that it's an async function and thus doesn't wait for it to resolve. This MR fixes that by respecting the fact that an async function may be given and waits till the promise is resolved.

### CODE REVIEW

**Comment by callumgare** [comment]
This is till applicable

**Comment by guumaster** [comment]
LGTM. Please @yahiakr can you review/approve?

**Comment by yahiakr** [comment]
Hey again,

LGTM! Can you please rebase with the `main` branch.

**Review by guumaster — APPROVED** [review]

**Comment by guumaster** [comment]
@callumgare I've tried to solve the conflicts but failed. Can you please review and fix it? Thanks!

Build log is here: https://github.com/mongoosastic/mongoosastic/runs/8020269505?check_suite_focus=true

**Comment by callumgare** [comment]
@guumaster Sorry for the slow reply! I've resolved the conflict now :)

**Pull request merged**
