### PR TITLE
Update the example folder

### PR DESCRIPTION
**Pull request by yahiakr**
Checklist: #576.

Re-write the example in TS, & update its dependencies.

### CODE REVIEW

**Comment by guumaster** [comment]
Is it possible to keep both example functional? maybe some people still want to use it in Node without Typescript.

**Comment by yahiakr** [comment]
> Is it possible to keep both example functional? maybe some people still want to use it in Node without Typescript.

I was thinking about creating two examples in both languages, i will update it.

**Comment by guumaster** [comment]
> > Is it possible to keep both example functional? maybe some people still want to use it in Node without Typescript.
> 
> I was thinking about creating two examples in both languages, i will update it.

yes, two folders sounds great! :+1:

**Comment by yahiakr** [comment]
> > > Is it possible to keep both example functional? maybe some people still want to use it in Node without Typescript.
> > 
> > 
> > I was thinking about creating two examples in both languages, i will update it.
> 
> yes, two folders sounds great! 👍
> 
> Maybe with this structure:
> 
> ```
> root/ 
>   examples/
>      node/
>      typescript/
> ```

I did it at the project level by creating two folders `/javascript` & `/typescript`. Since they share the same `static` resources.

**Comment by guumaster** [comment]
> > yes, two folders sounds great! +1
> > Maybe with this structure:
> > ```
> > root/ 
> >   examples/
> >      node/
> >      typescript/
> > ```
> 
> I did it at the project level by creating two folders `/javascript` & `/typescript`, since they share the same `static` resources.

Even better this way! I'll checkout and run both later

**Pull request merged**
