### PR TITLE
Added option forceIndexRefresh (see Issue #253)

### PR DESCRIPTION
**Pull request by enrichz**
I'm trying to resolve the issue #253 that I opened back in December.
It's a really simple fix and I hope you can include it in the stable release.
I read the guidelines for contributing, and I couldn't find the develop branch, so I forked the repository from master, but I can change this if you give me more instructions.
Also, I didn't write any test cases yet, because I don't know if this pull request will be accepted or not. I will provide the tests then.
Let me know.

Enrico

### CODE REVIEW

**Comment by isayme** [comment]
please add a test case

**Comment by enrichz** [comment]
I added the test cases both for save and findOneAndUpdate.
I named some tests as "should fail randomly", that's when an insert/update is not indexed immediately so these tests will succeed when the indexing is accomplished immediately and will fail otherwise.
The other tests ("should always succeed") MUST always pass because they have the option forceIndexRefresh set to true.
Anyway, it seems to me that the inconcistency happens less often than before, did you make some changes?
Let me know if you have any questions.
Thanks

**Comment by isayme** [comment]
@enrichz the travis ci failed, please fix them before code review.

**Comment by enrichz** [comment]
sorry about that this is my first pull request. Now it should be ok.

**Comment by enrichz** [comment]
@isayme what do you mean with generators?

**Comment by isayme** [comment]
@enrichz  we donot need callback anymore, since we have `co-mocha`~
```
it('xxx', function * () {
  yield xxx()
})
```

**Comment by enrichz** [comment]
any updates on this?

**Pull request merged**
