### PR TITLE
Enable document filtering while indexing

### LINKED ISSUE #66: Filtering option for save hook
Hi,
I am wondering if middlewarehook for saving to mongoose can be triggered for specific type of items instead of all of them.

For example:

Item: {
 type: es_index:true
 size: es_index:false
}

I can get all the items with type index in elasticsearch but what I want is to have only let's say items whose size are bigger than 20 to be indexed into elasticsearch.

Is the a way to do that?

### PR DESCRIPTION
**Pull request by cakuki**
Fixes #66

Do we need tests for that?

### CODE REVIEW

**Comment by guumaster** [comment]
Could you add some tests?

**Comment by skr** [comment]
@guumaster Added tests

**Comment by guumaster** [comment]
Thanks for the PR, if you could add a small example in the README, it would be great.

**Comment by cakuki** [comment]
Sure, will add it today.

**Pull request merged**
