### PR TITLE
Using postSave(doc) instead of doc.save(cb) in .synchronize()

### PR DESCRIPTION
**Pull request by DerekDomino**
Previously a `doc.save()` was triggered for synchronizing doc instance to ElasticSearch.

It means that before indexing doc instance to ElasticSearch, mongoose will process all pre-save hooks of the doc model.

It is undesirable since:
 * depending on the situation, some pre-save's can be costly
 * some pre-save methods can fail, thus the document is not indexed

PR replaces `doc.save(cb)` by `postSave(doc)`

Unit tests OK. Tested in production.

### CODE REVIEW

**Comment by fyockm** [comment]
:+1: Well done @DerekDomino - I was about to submit the same PR.

From what I can tell, re-saving the mongoose doc on `syncronize` is completely unnecessary. It not only slows the sync significantly, but as @DerekDomino mentioned, it causes undesirable pre-hooks to fire. For my particular use case, I have a pre-save hook to set a `lastUpdated` timestamp. I *do not* want the `mongoosastic` sync to change this timestamp for all my documents.

Also, it appears that the unit test failure is due to Travis inconsistencies, and not the actual code changes.

**Comment by DerekDomino** [comment]
OK, by running again Travis, tests are now successful.

**Comment by guumaster** [comment]
This seems ok, but if someone is relying on pre-save hooks to fill some computed fields those won't be indexed. Wouldn't be better if this behaviour were optional?

**Comment by DerekDomino** [comment]
What about an new option `triggerPreSaveOnSynchronize`which defaults to true:
````
MyModel.plugin(mongoosastic, {
  triggerPreSaveOnSynchronize: false
})
````

**Comment by DerekDomino** [comment]
... as well as for the `synchronize()` method:

````
Book.synchronize({}, {triggerPreSaveOnSynchronize: false});
// or
Book.synchronize({author: 'Chewbacca'}, {triggerPreSaveOnSynchronize: false});
````

**Comment by fyockm** [comment]
My recommendation would be to add the `triggerPreSaveOnSyncronize` option, but default to `false` instead of `true` because of efficiency. 
Looks like a major version bump will be coming with #144 anyhow, so this API change can be combined with the upgrade to ES2.x.

**Comment by DerekDomino** [comment]
Added the option (I went for `saveOnSynchronize`) + documentation in Readme.

No UT yet.

**Comment by guumaster** [comment]
We can use a compatible default value for the current version and remove the option for the next mayor release.

**Comment by DerekDomino** [comment]
OK, the default behaviour in this PR matches current version behaviour

**Comment by guumaster** [comment]
This seems ready to merge. Please squash it into a single commit.

**Comment by DerekDomino** [comment]
Again, I'm not able to squash commits in a single one.

**Comment by DerekDomino** [comment]
I've spent enough time about squashing the commits, no result.

**Comment by guumaster** [comment]
Yes, I've also tried with no success. Tests passes, but now the branch is behind and can't be auto-merged. Could you at least rebase it?

**Comment by DerekDomino** [comment]
This PR can be discarded.

I've reimplemented all the changes in a new branch starting from the latest master branch. See PR #200.

**Pull request closed without merging**
