### PR TITLE
added: skipping mongoose validation when synchronize

### PR DESCRIPTION
**Pull request by barczaG**
When using complex schemas it can be a pain to validate every document before indexing it.

### CODE REVIEW

**Comment by DerekDomino** [comment]
PR #153 already addresses this problem.

**Comment by DerekDomino** [comment]
See PR #200

**Comment by barczaG** [comment]
@DerekDomino I've tried the new feature in #200 but it still doesn't solve my problem (I need to save it but without validating). If make this PR compatible with #200 will you merge it?

**Comment by DerekDomino** [comment]
This PR should be closed/discarded.

PR #200 is identical to this PR (#171). It allows to synchronize without mongoose-saving (and hence, without mongoose-validating).

I've added some unit tests, see PR #205.

What you want is different: save on synchronize but don't validate document. This can be achieved at mongoose level, see [validateBeforeSave](http://mongoosejs.com/docs/guide.html#validateBeforeSave) mongoose schema option. Before calling synchronizing, you could call:
````
    schema.set('validateBeforeSave', false);
````
then once synchronisation is over, call it again with 'true'. However, it means that during the synchronisation process, any other document .save() won't be validated.

Another option would be to add an option in mongoosastic to use .insert() instead of .save():
````
MyModel.collection.insert(...)
```` 
In this case, all mongoose middleware will be bypassed.

**Comment by barczaG** [comment]
@DerekDomino thank you for the detailed answer :)

**Pull request closed without merging**
