### PR TITLE
Understand mongoose references and populate the doc before index

### LINKED ISSUE #8: Index referenced documents
https://github.com/jamescarr/mongoosastic/issues/101#issue-32205453

> I'm attempting to index referenced documents. (Without making them sub-documents)
> 
> For example;
> 
> ```
> var Author = mongoose.Schema({
>     name: { type: String }
> }):
> 
> var Page = mongoose.Schema({
>     title: { type: String },
>     author: { type: ObjectId, ref: 'Author' }
> });
> ```
> 
> After getting indexed this becomes something like this;
> 
> ```
> "author": {
>     _bsontype: "ObjectID",
>     id: "SYæSþ\n®àÊF$"
> },
> ```
> 
> Is there anyway to index the full referenced object instead of just the ObjectId?

### PR DESCRIPTION
**Pull request by evindor**
Fixes #8 #90 
```javascript
var Comment = new Schema({
    title: String
  , body: String
  , author: String
});


var User = new Schema({
    name: {type:String, es_indexed:true}
  , email: String
  , city: String
  , comments: {type: Schema.Types.ObjectId, ref: 'Comment',
    es_schema: Comment, es_indexed:true, es_select: 'title body'}
})

User.plugin(mongoosastic, {
  populate: [
    {path: 'comments', select: 'title body'}
  ]
})
```

### CODE REVIEW

**Comment by evindor** [comment]
Caveats:
1. You should provide your `ref` schema to `es_schema` in order to make a correct mapping
2. By default mongoosastic will index the whole schema. Provide an `es_select` field on your schema to pick specific fields.
3. The `populate` array is an array of the same options you pass to [mongoose Model.populate](http://mongoosejs.com/docs/api.html#model_Model.populate)

**Comment by evindor** [comment]
Hmm, locally and on one instance of travis the tests pass :/

**Comment by guumaster** [comment]
Thats because of the ES timing issue. Great adition. Thanks! I'll merge after disabling the iojs that is making the build fail.

**Comment by evindor** [comment]
Awesome, thanks!
Regarding code and API - as you can see you'll need to provide both `es_select` in the schema and `select` in the populate options.

Populate options are, if fact, passed to Model.populate as is, so it's possible to use familiar options and the full power of mongoose population. Because `path` is mandatory in this case, we are able to construct `es_select` for the schema fields from the `select` field in populate options. There way 2 ways of doing it:
1. Pass the `populate` array all the way to [`mapping-generator#getCleanTree`](https://github.com/mongoosastic/mongoosastic/pull/118/files#diff-a25470038b87ada40a78c3c23d19784eR162)
2. Before calling [`getMapping`](https://github.com/mongoosastic/mongoosastic/pull/118/files#diff-995b1ef1b04a343d8a5ae6443c735508R155) we may iterate over `populate` and apply `es_select` fields to the `schema`. Then, we pass the modified schema to `getMapping`.

I don't like option 1 because it's messy and will require a lot of modifications to both code and tests.
Option 2 is more sane, but I'm not happy with modifying the original schema.

Me and my colleagues are fine with having both fields, like we already have in this PR. then, I can't come up with an example, but is there a case when you would like to have different things in `es_select` and `select` options? Maybe having both options is not a flaw but rather a feature? As an argument to that I can say that `es_select` helps you map you schema correctly, while `select` is a part of mongoose populate options object and controls what are you populating.

**Comment by guumaster** [comment]
TravisCI is updated now only with latests NodeJS versions. I've tried to rebuild your PR but it keeps failing. Could you check them and re-open the PR?. This would be a useful feature to add. Thanks

**Comment by nvartolomei** [comment]
This is very needed indeed, @evindor any news?

**Comment by juanpujol** [comment]
I did exaclty how it's explaned and I can't populate a ref on my model. I only get the id. Is this working as it should on the current version? 3.6.0.

Thank you.

**Comment by juanpujol** [comment]
@evindor the population works on 3.6.1 (it's great!), but then my queries stopped working.  The only way I can retrive things is with `{ match_all: {}}` can't query anymore.

If I reindex everything without the populate the queries work fine.

Are familiar with this issue?

Thank you

**Comment by TD-Stanley** [comment]
I swear i'm following this exactly, but I only get an empty object for the referenced object. When hydrated, it only sows the initial mongoose.ObjectId .

**Comment by jwzh222** [comment]
var Comment = new Schema({
    title: String
  , body: String
  , author: String
});
var User = new Schema({
    name: {type:String, es_indexed:true}
  , email: String
  , city: {type:String, es_indexed:true}
  , comments: {type: Schema.Types.ObjectId, ref: 'Comment',
    es_schema: Comment, es_indexed:true, es_select: 'title body'}
})
User.plugin(mongoosastic, {
  populate: [
    {path: 'comments', select: 'title body'}
  ]
})

our data:
User1: city:A  (ref)comments:{title: 'sad'}
User2: city:A  (ref)comments:{title: 'happy'}
User3: city:B  (ref)comments:{title: 'happy'}

my question:
how can i use es search to get data by this condition: city=A and title='happy'

/api/1.js:
My trying:
But the result of this script lost comments field, how can i populate comments and filter the title field?
User.search({
        query: {
            bool: {
                should: [{match: {city : 'A'}}]
            }
        }
    }, 
        (err,results)=>{
            if(err) console.log(err);
        res.send(results);
    });

plz help

**Pull request closed without merging**
