### PR TITLE
Fixes linting errors and updates dependencies  

### LINKED ISSUE #450: Make tests green again
This project needs help to get passing tests and update dependencies.

Maybe we can find some help in #hacktoberfest.

### PR DESCRIPTION
**Pull request by marshallford**
Hopefully resolves #450. I tried to start a ES container locally to test, but `npm run test` was either failing silently or taking along time. Travis should let me know what I did wrong :)

### CODE REVIEW

**Comment by marshallford** [comment]
So a couple notes regarding the CI results:

1. Node 4 without the harmony flag, does not support the rest/spread syntax.
2. From what I can tell, during the stable node run, the failing tests are related to either the version of the elasticsearch npm module or the version of elasticsearch that Travis is testing against.

Please let me know how you want to proceed. Do you still want to support Node 4? I assume you want to support the latest ES version?

**Comment by IGZgustavomarin** [comment]
I've started a new `develop` branch. I'll merge more often there until we get our tests back to green. 

Right now it includes mainly what you did here. Would you mind to continue from this branch?.  Feel free to change versions or .travis-ci.yml config. Whatever we need get our test suite back.

**Comment by marshallford** [comment]
@guumaster I'll take a look this evening and merge my changes into `develop`. I'm not sure what you mean by another ES configuration. My guess is the ES API changed. Take a look at this [failing test](https://travis-ci.org/mongoosastic/mongoosastic/jobs/439914435#L1207) for example, it appears that `hits` has changed locations within the response object?

**Comment by guumaster** [comment]
It's been a while since I used ES. I need to reinstall and run tests on debug mode to adapt to all libraries and API changes that may be there.

**Comment by guumaster** [comment]
I'm closing this as we already have fixed passing tests on `develop` branch. Thanks!

**Pull request closed without merging**
