### PR TITLE
Add support for ElasticSearch 2.x

### PR DESCRIPTION
**Pull request by Alexandre-io**
- Remove _id from bulk object. Prevent ElasticSearch to remap the _id into a string.
- Update tests to match ElasticSearch 2.x errors.
- es_index_analyzer and es_search_analyzer are merged to es_analyzer.
- Remove esTruncate since deleteByQuery was removed from native API.
- Bump elasticsearch.js from 8.x to 9.x (Default API bump from 1.7 to 2.0)

### CODE REVIEW

**Comment by Alexandre-io** [comment]
@guumaster Cloud you please review the merge ? thx

**Comment by Alexandre-io** [comment]
@guumaster Hi, Cloud you please review ? Thanks!

**Comment by guumaster** [comment]
We shouldn't just remove this feature. It must be optional and configurable through options to support users who still need ES < 2.0. Also we shouldn't remove tests, instead, add more to catch all possible usages.

**Comment by Alexandre-io** [comment]
Totally agree but how we can deal with it ?
The deleteByQuery was removed from the native api so you must have the package elasticsearch <= 9.x.x to support the feature and >9.x.x to work with ES 2.x API.

**Comment by Alexandre-io** [comment]
Here is a workaround to keep esTruncate.

**Comment by Alexandre-io** [comment]
- Remove _id from bulk object. Prevent ElasticSearch to remap the _id into a string.
- Update tests to match ElasticSearch 2.x errors.
- es_index_analyzer and es_search_analyzer are merged to es_analyzer.
- Refactor esTruncate since deleteByQuery was removed from native API.
- Bump elasticsearch.js from 8.x to 10.x (Default API bump from 1.7 to 2.1)
- Dependencies upgrade
- Beautify code to match eslint recommandations

**Comment by guumaster** [comment]
This contains lots and lots of changes not related to the feature, I can't review all of that and find out which ones are style changes and feature changes. Could you minimize the changes just to the feature and only that?
For example: 
- don't update dependencies, only the ones you need. 
- don't change travis.yml
- don't deactivate any eslint rules
- don't change style or indentation nor reformat any object literal. 
- squash all commits into only 

Those are not bad, just doesn't belong to this specific PR, you can send them with new PRs, the more specific the PR, the better.

**Pull request closed without merging**
