### PR TITLE
Raw search: providing unwrapped query object. For paging, for example.

### PR DESCRIPTION
**Pull request by DerekDomino**
Default `.search()` method accepts as argument a query that will be wrapped by mongoosastic. 
 
This PR adds a new method accepting a raw (unwrapped) query object. Can be useful for paging results.

### CODE REVIEW

**Comment by guumaster** [comment]
This should have been the default method of querying. Nice addition. Could you squash it into a single commit? Thanks

**Comment by nschloe** [comment]
Definitely something I'm looking forward too as well. Great work!

(I don't understand why anyone should have to go through the hassle of squashing the commits into one though.)

**Comment by guumaster** [comment]
Its easier to track features and avoid merging commits like "indentation rollback". 

I'm on my phone now, I'll add a simple example using git reset later.

**Comment by DerekDomino** [comment]
I just tried to squash them without success. Could you please try it?

**Comment by nschloe** [comment]
> Its easier to track features and avoid merging commits like "indentation rollback".

I was asking because I'd never seen such a policy, and it appears to keep people from contributing their code. And I'm anxiously waiting for this PR to get merged. :)

**Comment by guumaster** [comment]
Sorry for the delay. See #163 to discuss if we should make a mayor bump and change the default `.search()` behaviour instead of adding another method.

**Comment by glortho** [comment]
+1 for major bump. imo this should be default behavior.

**Comment by DerekDomino** [comment]
I've spent several hours about trying to squash it: unsuccessful.
I don't want to spent more time about aesthetic stuff and non-essential work.

Ready for merge, isn't?

**Comment by nschloe** [comment]
@guumaster GitHub now supports squash-merges, cf. https://github.com/blog/2141-squash-your-commits.

**Comment by guumaster** [comment]
Cool, but can't change that setting. I'll have to ask to @taterbase or @github directly to change it. I'll merge after enabling it.

**Pull request merged**
