### PR TITLE
index/unindex when findOneAndUpdate/findOneAndRemove

### PR DESCRIPTION
**Pull request by isayme**
Mongoose support findOneAndUpdate/findOneAndRemove middlewares since version 4.0, 
so we can index/unindex documents with the help of the new middlewares now~~

Refers:
[Middleware](http://mongoosejs.com/docs/middleware.html#notes)
[pre, post middleware are not executed on findByIdAndUpdate](https://github.com/Automattic/mongoose/issues/964)

### CODE REVIEW

**Comment by guumaster** [comment]
seems good, but *Travis says no*, it triggers a `RangeError: Maximum call stack size exceeded` while testing. Could you check?

**Comment by isayme** [comment]
Yes...  I will check the reason~~

**Comment by isayme** [comment]
@guumaster currently, mongoosastic use elasticsearch5.x.

in latest iojs, [Class Method: EventEmitter.listenerCount(emitter, event)](https://iojs.org/api/events.html#events_class_method_eventemitter_listenercount_emitter_event) has deprecated, while this method still used in elasticsearch5.x.

And as I checked, elasticsearch fixed this problem in version 8.x(commit [Add support for EE#listenerCount()](https://github.com/elastic/elasticsearch-js/commit/f2a0cede2eff793dd894ee8bef2a2e051f6bafe6)).

so we should update elasticsearch to 8.x in package.json~

**Comment by michelem09** [comment]
I found an option to be set with Mongoose >= 4.x if you want to use `findOneAndUpdate` or any `update` methods and get indexed: you have to set the option `{new: true}`

If you don't set that, Mongoose return to Mongoosastic the old value instead the updated one.

Reference: https://github.com/Automattic/mongoose/issues/2262

> In Mongoose doc http://mongoosejs.com/docs/api.html#model_Model.findOneAndUpdate
> new: bool - true to return the modified document rather than the original. defaults to true

**This was changed in 4.x to be default to false**

https://github.com/Automattic/mongoose/wiki/4.0-Release-Notes

So for example, this query DOESN'T update the ES index, because it misses the `{new: true}` option:

```
Collection.findOneAndUpdate({ sku: 'test-678' }, {$set: {title: 'HELLO'}}, { upsert : true }, function(err, doc) {
	if (err) console.log(err);
        // doc is the old MongoDB document
});
```

**While this one update also the ES index with Mongosastic:**

```
Catalog.findOneAndUpdate({ sku: 'test-678' }, {$set: {title: 'HELLO'}}, { upsert : true, new: true }, function(err, doc) {
	if (err) console.log(err);
        // now doc is the new modifed MongoDB document
});
```

I can't find this in the Mongoosastic documentation and I kept some time before find it perhaps it deserves a comment somewhere.

**Pull request merged**
