### PR TITLE
You can map id to elastic search with es_indexed: true now

### PR DESCRIPTION
**Pull request by danielstaleiny**
Solving issue with mapping id even when is es_indexed: true
test to see if it works

### CODE REVIEW

**Comment by guumaster** [comment]
Could you do a minor change? Check if it works with the standard `global.Promise` we don't have bluebird as a dependency

**Comment by danielstaleiny** [comment]
Sure thing but global.Promise is deprecated that is why  I changed it.

**Comment by isayme** [comment]
I would prefer `continue` only when `id` is a virtual field.

**Comment by danielstaleiny** [comment]
what do you mean by virtual field ? generated by mongo ?

**Comment by isayme** [comment]
@danielstaleiny 
1. the added tests should not create real document since we are testing create mappings;
2. replace `if (prefix === '' && (field === 'id' || field === '_id')) {` with `if (prefix === '' && field === '_id') {`, see comment `// If it's a virtual type, don't map it` in source code.

**Comment by danielstaleiny** [comment]
@isayme I changed tests to test mapping without creating data and changed if  statement so it doesn't check for `id` at all :)

**Comment by isayme** [comment]
@danielstaleiny could you please squash your commits to one single commit ?

see http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html if you need help.

**Comment by guumaster** [comment]
@isayme there is no need to squash commits anymore, Github implemented that in the merge button. Is easier for people to collaborate.

**Comment by isayme** [comment]
@guumaster got~

**Pull request closed without merging**
