### PR TITLE
Develop (test fixes)

### PR DESCRIPTION
**Pull request by AxelJunker**
Tested on:

- elasticsearch@15.4.1
- mongoose@5.5.1
- ElasticSearch 6.7
- MongoDB 4.0.4
- NodeJS 10.15.0
- NPM 6.9.0

I haven't tested against any other versions and I think there are some breaking changes. 

One of the tests (alternative-index-method-test.js -> 'should be able to index to alternative index and type') can not pass in ElasticSearch > 6.x.

I did not manage to pass the test: 'should serialize a document with missing bits' (serialize-test.js)

The rest should be fine!

### CODE REVIEW

**Comment by guumaster** [comment]
@AxelJunker It seems that there are some conflicts to merge this because your fork started from an early commit with older dependencies. 

Could you merge the latest `develop` branch onto yours and upload the changes? that should allow the pipeline to run and we can see the tests output. 

Here you have a guide on how to [merge changes from upstream (original mongoosastic) to your fork](https://help.github.com/en/articles/merging-an-upstream-repository-into-your-fork)

**Comment by AxelJunker** [comment]
@guumaster hm, it says "Already up to date" when I `git pull https://github.com/mongoosastic/mongoosastic.git develop`.

When I started, I forked the repo and created a local branch with starting point from master. Then I merged the changes onto develop. In hindsight, I know I shouldn't merge from master to develop. Should I merge the changes onto master instead?

**Comment by AxelJunker** [comment]
@guumaster just let me know if there's anything I can do :)

**Comment by guumaster** [comment]
Not sure how to help here. If you start from latest commit from `mongoosastic:develop`, all your commits should be upon that, instead of behind.

**Comment by guumaster** [comment]
Close in favor of #469

**Pull request closed without merging**
