### PR TITLE
Add filter to avoid crash if document is not in db but it is in ES.

### PR DESCRIPTION
**Pull request by elvizcacho**

### CODE REVIEW

**Comment by isayme** [comment]
how could we know the document not in db ?

**Comment by elvizcacho** [comment]
@isayme The documents are requested from mongoDB using the _ids from the ES result. https://github.com/mongoosastic/mongoosastic/blob/master/lib/mongoosastic.js#L122
now, imagine that one of the documents is not in the mongoDB anymore. Then ```docMap``` object is populated 
https://github.com/mongoosastic/mongoosastic/blob/master/lib/mongoosastic.js#L141
using the mongoDB results only. Then you map the results from mongo using the ES _ids to preserve ES order what will create and undefined entry in the hits array as one of the _ids from ES result doesn't have any value in ```docMap```.
https://github.com/mongoosastic/mongoosastic/blob/master/lib/mongoosastic.js#L144
This undefined entry in the ```hits```array will through an exception in https://github.com/mongoosastic/mongoosastic/blob/master/lib/mongoosastic.js#L149

That's why I added this filter to remove any undefined entry. Maybe there is a more elegant solution. Let me know your thoughts about this.

**Comment by guumaster** [comment]
@elvizcacho could you add some test cases please?

**Comment by guumaster** [comment]
This PR is too old. Closing due to changes in the `develop` branch. Please re-open with test cases if you need this. Thanks!

**Pull request closed without merging**
